'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace Sap_Create
    
    'CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_BP_CREATE", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZWS_BP_CREATE
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZFM_BP_SERVICES_CREATEOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.tlgSapCooperacion.My.MySettings.Default.tlgSapCooperacion_Sap_Create_ZWS_BP_CREATE
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZFM_BP_SERVICES_CREATECompleted As ZFM_BP_SERVICES_CREATECompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZWS_BP_CREATE:ZFM_BP_SERVICES_CREATEReques"& _ 
            "t", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZFM_BP_SERVICES_CREATE(<System.Xml.Serialization.XmlElementAttribute("ZFM_BP_SERVICES_CREATE", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZFM_BP_SERVICES_CREATE1 As ZFM_BP_SERVICES_CREATE) As <System.Xml.Serialization.XmlElementAttribute("ZFM_BP_SERVICES_CREATEResponse", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZFM_BP_SERVICES_CREATEResponse
            Dim results() As Object = Me.Invoke("ZFM_BP_SERVICES_CREATE", New Object() {ZFM_BP_SERVICES_CREATE1})
            Return CType(results(0),ZFM_BP_SERVICES_CREATEResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZFM_BP_SERVICES_CREATEAsync(ByVal ZFM_BP_SERVICES_CREATE1 As ZFM_BP_SERVICES_CREATE)
            Me.ZFM_BP_SERVICES_CREATEAsync(ZFM_BP_SERVICES_CREATE1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZFM_BP_SERVICES_CREATEAsync(ByVal ZFM_BP_SERVICES_CREATE1 As ZFM_BP_SERVICES_CREATE, ByVal userState As Object)
            If (Me.ZFM_BP_SERVICES_CREATEOperationCompleted Is Nothing) Then
                Me.ZFM_BP_SERVICES_CREATEOperationCompleted = AddressOf Me.OnZFM_BP_SERVICES_CREATEOperationCompleted
            End If
            Me.InvokeAsync("ZFM_BP_SERVICES_CREATE", New Object() {ZFM_BP_SERVICES_CREATE1}, Me.ZFM_BP_SERVICES_CREATEOperationCompleted, userState)
        End Sub
        
        Private Sub OnZFM_BP_SERVICES_CREATEOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZFM_BP_SERVICES_CREATECompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZFM_BP_SERVICES_CREATECompleted(Me, New ZFM_BP_SERVICES_CREATECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZFM_BP_SERVICES_CREATE
        
        Private iS_BP_CREATEField As ZST_BP_CREATE_IN_WS
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IS_BP_CREATE() As ZST_BP_CREATE_IN_WS
            Get
                Return Me.iS_BP_CREATEField
            End Get
            Set
                Me.iS_BP_CREATEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS
        
        Private bASICOSField As ZST_BP_CREATE_IN_WS_BASICOS
        
        Private rOLESField() As ZST_BP_BU_PARTNERROLE
        
        Private pERSONAField As ZST_BP_CREATE_IN_WS_PERSONA
        
        Private eMPRESAField As ZST_BP_CREATE_IN_WS_EMPRESA
        
        Private iDENTIFICACIONField() As ZST_BP_CREATE_IN_WS_IDENT
        
        Private dIRECCIONESField() As ZST_BP_CREATE_IN_WS_DIRECCION
        
        Private cONTACTOField As ZST_BP_CREATE_IN_WS_CONTACTO
        
        Private bANCARIOSField() As ZST_BP_CREATE_IN_WS_BANCO
        
        Private tARJETASField() As ZST_BP_CREATE_IN_WS_TARJETA
        
        Private iMPUESTOSField() As ZST_BP_CREATE_IN_WS_IMPUESTOS
        
        Private zAMP1Field As ZST_BP_CREATE_IN_WS_AMP1
        
        Private cLIENTEField As ZST_BP_CREATE_IN_WS_CLIENTE
        
        Private pROVEEDORField As ZST_BP_CREATE_IN_WS_PROVEEDOR
        
        Private gESTORField As ZST_BP_GESTOR_WS
        
        Private rELACIONESField() As ZST_BP_WS_CREATE_REL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BASICOS() As ZST_BP_CREATE_IN_WS_BASICOS
            Get
                Return Me.bASICOSField
            End Get
            Set
                Me.bASICOSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property ROLES() As ZST_BP_BU_PARTNERROLE()
            Get
                Return Me.rOLESField
            End Get
            Set
                Me.rOLESField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PERSONA() As ZST_BP_CREATE_IN_WS_PERSONA
            Get
                Return Me.pERSONAField
            End Get
            Set
                Me.pERSONAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EMPRESA() As ZST_BP_CREATE_IN_WS_EMPRESA
            Get
                Return Me.eMPRESAField
            End Get
            Set
                Me.eMPRESAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IDENTIFICACION() As ZST_BP_CREATE_IN_WS_IDENT()
            Get
                Return Me.iDENTIFICACIONField
            End Get
            Set
                Me.iDENTIFICACIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property DIRECCIONES() As ZST_BP_CREATE_IN_WS_DIRECCION()
            Get
                Return Me.dIRECCIONESField
            End Get
            Set
                Me.dIRECCIONESField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CONTACTO() As ZST_BP_CREATE_IN_WS_CONTACTO
            Get
                Return Me.cONTACTOField
            End Get
            Set
                Me.cONTACTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property BANCARIOS() As ZST_BP_CREATE_IN_WS_BANCO()
            Get
                Return Me.bANCARIOSField
            End Get
            Set
                Me.bANCARIOSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TARJETAS() As ZST_BP_CREATE_IN_WS_TARJETA()
            Get
                Return Me.tARJETASField
            End Get
            Set
                Me.tARJETASField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property IMPUESTOS() As ZST_BP_CREATE_IN_WS_IMPUESTOS()
            Get
                Return Me.iMPUESTOSField
            End Get
            Set
                Me.iMPUESTOSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZAMP1() As ZST_BP_CREATE_IN_WS_AMP1
            Get
                Return Me.zAMP1Field
            End Get
            Set
                Me.zAMP1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLIENTE() As ZST_BP_CREATE_IN_WS_CLIENTE
            Get
                Return Me.cLIENTEField
            End Get
            Set
                Me.cLIENTEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PROVEEDOR() As ZST_BP_CREATE_IN_WS_PROVEEDOR
            Get
                Return Me.pROVEEDORField
            End Get
            Set
                Me.pROVEEDORField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GESTOR() As ZST_BP_GESTOR_WS
            Get
                Return Me.gESTORField
            End Get
            Set
                Me.gESTORField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property RELACIONES() As ZST_BP_WS_CREATE_REL()
            Get
                Return Me.rELACIONESField
            End Get
            Set
                Me.rELACIONESField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_BASICOS
        
        Private tIPOField As String
        
        Private bLOQUEADOField As String
        
        Private aCTIVOField As String
        
        Private bUSQUEDA1Field As String
        
        Private bUSQUEDA2Field As String
        
        Private cLASEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIPO() As String
            Get
                Return Me.tIPOField
            End Get
            Set
                Me.tIPOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BLOQUEADO() As String
            Get
                Return Me.bLOQUEADOField
            End Get
            Set
                Me.bLOQUEADOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ACTIVO() As String
            Get
                Return Me.aCTIVOField
            End Get
            Set
                Me.aCTIVOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BUSQUEDA1() As String
            Get
                Return Me.bUSQUEDA1Field
            End Get
            Set
                Me.bUSQUEDA1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BUSQUEDA2() As String
            Get
                Return Me.bUSQUEDA2Field
            End Get
            Set
                Me.bUSQUEDA2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASE() As String
            Get
                Return Me.cLASEField
            End Get
            Set
                Me.cLASEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class BAPIRET2
        
        Private tYPEField As String
        
        Private idField As String
        
        Private nUMBERField As String
        
        Private mESSAGEField As String
        
        Private lOG_NOField As String
        
        Private lOG_MSG_NOField As String
        
        Private mESSAGE_V1Field As String
        
        Private mESSAGE_V2Field As String
        
        Private mESSAGE_V3Field As String
        
        Private mESSAGE_V4Field As String
        
        Private pARAMETERField As String
        
        Private rOWField As Integer
        
        Private fIELDField As String
        
        Private sYSTEMAField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TYPE() As String
            Get
                Return Me.tYPEField
            End Get
            Set
                Me.tYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMBER() As String
            Get
                Return Me.nUMBERField
            End Get
            Set
                Me.nUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MESSAGE() As String
            Get
                Return Me.mESSAGEField
            End Get
            Set
                Me.mESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LOG_NO() As String
            Get
                Return Me.lOG_NOField
            End Get
            Set
                Me.lOG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LOG_MSG_NO() As String
            Get
                Return Me.lOG_MSG_NOField
            End Get
            Set
                Me.lOG_MSG_NOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MESSAGE_V1() As String
            Get
                Return Me.mESSAGE_V1Field
            End Get
            Set
                Me.mESSAGE_V1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MESSAGE_V2() As String
            Get
                Return Me.mESSAGE_V2Field
            End Get
            Set
                Me.mESSAGE_V2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MESSAGE_V3() As String
            Get
                Return Me.mESSAGE_V3Field
            End Get
            Set
                Me.mESSAGE_V3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MESSAGE_V4() As String
            Get
                Return Me.mESSAGE_V4Field
            End Get
            Set
                Me.mESSAGE_V4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARAMETER() As String
            Get
                Return Me.pARAMETERField
            End Get
            Set
                Me.pARAMETERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ROW() As Integer
            Get
                Return Me.rOWField
            End Get
            Set
                Me.rOWField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FIELD() As String
            Get
                Return Me.fIELDField
            End Get
            Set
                Me.fIELDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SYSTEMA() As String
            Get
                Return Me.sYSTEMAField
            End Get
            Set
                Me.sYSTEMAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class CVIS_MESSAGE
        
        Private iS_ERRORField As String
        
        Private mESSAGESField() As BAPIRET2
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IS_ERROR() As String
            Get
                Return Me.iS_ERRORField
            End Get
            Set
                Me.iS_ERRORField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property MESSAGES() As BAPIRET2()
            Get
                Return Me.mESSAGESField
            End Get
            Set
                Me.mESSAGESField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_OUT_WS_DIRECCION
        
        Private cODIGO_SAPField As String
        
        Private cODIGO_EXTERNOField As String
        
        Private cONTACTOField As ZST_BP_CREATE_IN_WS_CONTACTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_SAP() As String
            Get
                Return Me.cODIGO_SAPField
            End Get
            Set
                Me.cODIGO_SAPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_EXTERNO() As String
            Get
                Return Me.cODIGO_EXTERNOField
            End Get
            Set
                Me.cODIGO_EXTERNOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CONTACTO() As ZST_BP_CREATE_IN_WS_CONTACTO
            Get
                Return Me.cONTACTOField
            End Get
            Set
                Me.cONTACTOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_CONTACTO
        
        Private tELEFONOSField() As ZST_BP_TELEFONO
        
        Private eMAILSField() As ZST_BP_EMAIL
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TELEFONOS() As ZST_BP_TELEFONO()
            Get
                Return Me.tELEFONOSField
            End Get
            Set
                Me.tELEFONOSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EMAILS() As ZST_BP_EMAIL()
            Get
                Return Me.eMAILSField
            End Get
            Set
                Me.eMAILSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_TELEFONO
        
        Private iD_NUMEROField As String
        
        Private eS_PRINCIPALField As String
        
        Private eS_MOVILField As String
        
        Private cON_FAXField As String
        
        Private nUMEROField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ID_NUMERO() As String
            Get
                Return Me.iD_NUMEROField
            End Get
            Set
                Me.iD_NUMEROField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ES_PRINCIPAL() As String
            Get
                Return Me.eS_PRINCIPALField
            End Get
            Set
                Me.eS_PRINCIPALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ES_MOVIL() As String
            Get
                Return Me.eS_MOVILField
            End Get
            Set
                Me.eS_MOVILField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CON_FAX() As String
            Get
                Return Me.cON_FAXField
            End Get
            Set
                Me.cON_FAXField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMERO() As String
            Get
                Return Me.nUMEROField
            End Get
            Set
                Me.nUMEROField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_EMAIL
        
        Private iD_EMAILField As String
        
        Private eS_PRINCIPALField As String
        
        Private eMAILField As String
        
        Private cOMENTARIOField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ID_EMAIL() As String
            Get
                Return Me.iD_EMAILField
            End Get
            Set
                Me.iD_EMAILField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ES_PRINCIPAL() As String
            Get
                Return Me.eS_PRINCIPALField
            End Get
            Set
                Me.eS_PRINCIPALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EMAIL() As String
            Get
                Return Me.eMAILField
            End Get
            Set
                Me.eMAILField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COMENTARIO() As String
            Get
                Return Me.cOMENTARIOField
            End Get
            Set
                Me.cOMENTARIOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_OUT_WS
        
        Private cODIGO_SAPField As String
        
        Private cODIGO_EXTERNOField As String
        
        Private dIREECCIONESField() As ZST_BP_CREATE_OUT_WS_DIRECCION
        
        Private cONTACTOField As ZST_BP_CREATE_IN_WS_CONTACTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_SAP() As String
            Get
                Return Me.cODIGO_SAPField
            End Get
            Set
                Me.cODIGO_SAPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_EXTERNO() As String
            Get
                Return Me.cODIGO_EXTERNOField
            End Get
            Set
                Me.cODIGO_EXTERNOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property DIREECCIONES() As ZST_BP_CREATE_OUT_WS_DIRECCION()
            Get
                Return Me.dIREECCIONESField
            End Get
            Set
                Me.dIREECCIONESField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CONTACTO() As ZST_BP_CREATE_IN_WS_CONTACTO
            Get
                Return Me.cONTACTOField
            End Get
            Set
                Me.cONTACTOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_WS_CREATE_REL
        
        Private bP_RELACIONADOField As String
        
        Private rELACIONField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BP_RELACIONADO() As String
            Get
                Return Me.bP_RELACIONADOField
            End Get
            Set
                Me.bP_RELACIONADOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property RELACION() As String
            Get
                Return Me.rELACIONField
            End Get
            Set
                Me.rELACIONField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_GESTOR_WS
        
        Private oRIGENField As String
        
        Private dISPONIBLEField As String
        
        Private vALIDOField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ORIGEN() As String
            Get
                Return Me.oRIGENField
            End Get
            Set
                Me.oRIGENField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DISPONIBLE() As String
            Get
                Return Me.dISPONIBLEField
            End Get
            Set
                Me.dISPONIBLEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO() As String
            Get
                Return Me.vALIDOField
            End Get
            Set
                Me.vALIDOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_PROVEEDOR
        
        Private cLASE_IMPUESTOField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASE_IMPUESTO() As String
            Get
                Return Me.cLASE_IMPUESTOField
            End Get
            Set
                Me.cLASE_IMPUESTOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CATEG_FISCALES
        
        Private cATEG_FISCALField As String
        
        Private vALIDO_DESDEField As String
        
        Private vALIDO_HASTAField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CATEG_FISCAL() As String
            Get
                Return Me.cATEG_FISCALField
            End Get
            Set
                Me.cATEG_FISCALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_DESDE() As String
            Get
                Return Me.vALIDO_DESDEField
            End Get
            Set
                Me.vALIDO_DESDEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_HASTA() As String
            Get
                Return Me.vALIDO_HASTAField
            End Get
            Set
                Me.vALIDO_HASTAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_CLIENTE
        
        Private cLASE_IMPUESTOField As String
        
        Private cATEG_FISCALESField() As ZST_BP_CATEG_FISCALES
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASE_IMPUESTO() As String
            Get
                Return Me.cLASE_IMPUESTOField
            End Get
            Set
                Me.cLASE_IMPUESTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property CATEG_FISCALES() As ZST_BP_CATEG_FISCALES()
            Get
                Return Me.cATEG_FISCALESField
            End Get
            Set
                Me.cATEG_FISCALESField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_AMP1
        
        Private zWS_ESPEPField As String
        
        Private zCODACTField As String
        
        Private zACTIVIDADField As String
        
        Private zPERFIL_PLA_PATOPEField As String
        
        Private zPERFIL_PLA_FECALTAField As String
        
        Private zINVESTIGADO_UIFField As String
        
        Private zREQUERIDO_UIF_SSNField As String
        
        Private zDOC_PERFIL_PLAField As String
        
        Private zLATITUDField As String
        
        Private zLONGITUDField As String
        
        Private fECALTAField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZWS_ESPEP() As String
            Get
                Return Me.zWS_ESPEPField
            End Get
            Set
                Me.zWS_ESPEPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZCODACT() As String
            Get
                Return Me.zCODACTField
            End Get
            Set
                Me.zCODACTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZACTIVIDAD() As String
            Get
                Return Me.zACTIVIDADField
            End Get
            Set
                Me.zACTIVIDADField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPERFIL_PLA_PATOPE() As String
            Get
                Return Me.zPERFIL_PLA_PATOPEField
            End Get
            Set
                Me.zPERFIL_PLA_PATOPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPERFIL_PLA_FECALTA() As String
            Get
                Return Me.zPERFIL_PLA_FECALTAField
            End Get
            Set
                Me.zPERFIL_PLA_FECALTAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZINVESTIGADO_UIF() As String
            Get
                Return Me.zINVESTIGADO_UIFField
            End Get
            Set
                Me.zINVESTIGADO_UIFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZREQUERIDO_UIF_SSN() As String
            Get
                Return Me.zREQUERIDO_UIF_SSNField
            End Get
            Set
                Me.zREQUERIDO_UIF_SSNField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZDOC_PERFIL_PLA() As String
            Get
                Return Me.zDOC_PERFIL_PLAField
            End Get
            Set
                Me.zDOC_PERFIL_PLAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLATITUD() As String
            Get
                Return Me.zLATITUDField
            End Get
            Set
                Me.zLATITUDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZLONGITUD() As String
            Get
                Return Me.zLONGITUDField
            End Get
            Set
                Me.zLONGITUDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FECALTA() As String
            Get
                Return Me.fECALTAField
            End Get
            Set
                Me.fECALTAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_IMPUESTOS
        
        Private tIPO_IMPField As String
        
        Private nUMERO_IMPField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIPO_IMP() As String
            Get
                Return Me.tIPO_IMPField
            End Get
            Set
                Me.tIPO_IMPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMERO_IMP() As String
            Get
                Return Me.nUMERO_IMPField
            End Get
            Set
                Me.nUMERO_IMPField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_TARJ_LOKS
        
        Private mOTIVOField As String
        
        Private vALIDO_DESDEField As String
        
        Private vALIDO_HASTAField As String
        
        Private bORRAR_BLOQUEOField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MOTIVO() As String
            Get
                Return Me.mOTIVOField
            End Get
            Set
                Me.mOTIVOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_DESDE() As String
            Get
                Return Me.vALIDO_DESDEField
            End Get
            Set
                Me.vALIDO_DESDEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_HASTA() As String
            Get
                Return Me.vALIDO_HASTAField
            End Get
            Set
                Me.vALIDO_HASTAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BORRAR_BLOQUEO() As String
            Get
                Return Me.bORRAR_BLOQUEOField
            End Get
            Set
                Me.bORRAR_BLOQUEOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_TARJETA
        
        Private idField As String
        
        Private eS_PRINCIPALField As String
        
        Private eMPRESAField As String
        
        Private nUMEROField As String
        
        Private dENOMINACIONField As String
        
        Private vALIDO_DESDEField As String
        
        Private vALIDO_HASTAField As String
        
        Private bANCO_EMISORField As String
        
        Private fECHA_EMISIONField As String
        
        Private bLOQUEOSField() As ZST_BP_CREATE_IN_WS_TARJ_LOKS
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ES_PRINCIPAL() As String
            Get
                Return Me.eS_PRINCIPALField
            End Get
            Set
                Me.eS_PRINCIPALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EMPRESA() As String
            Get
                Return Me.eMPRESAField
            End Get
            Set
                Me.eMPRESAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMERO() As String
            Get
                Return Me.nUMEROField
            End Get
            Set
                Me.nUMEROField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DENOMINACION() As String
            Get
                Return Me.dENOMINACIONField
            End Get
            Set
                Me.dENOMINACIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_DESDE() As String
            Get
                Return Me.vALIDO_DESDEField
            End Get
            Set
                Me.vALIDO_DESDEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_HASTA() As String
            Get
                Return Me.vALIDO_HASTAField
            End Get
            Set
                Me.vALIDO_HASTAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANCO_EMISOR() As String
            Get
                Return Me.bANCO_EMISORField
            End Get
            Set
                Me.bANCO_EMISORField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FECHA_EMISION() As String
            Get
                Return Me.fECHA_EMISIONField
            End Get
            Set
                Me.fECHA_EMISIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property BLOQUEOS() As ZST_BP_CREATE_IN_WS_TARJ_LOKS()
            Get
                Return Me.bLOQUEOSField
            End Get
            Set
                Me.bLOQUEOSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_BANCO
        
        Private pAISField As String
        
        Private cODIGOField As String
        
        Private cUENTAField As String
        
        Private cBUField As String
        
        Private tIPOField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PAIS() As String
            Get
                Return Me.pAISField
            End Get
            Set
                Me.pAISField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO() As String
            Get
                Return Me.cODIGOField
            End Get
            Set
                Me.cODIGOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CUENTA() As String
            Get
                Return Me.cUENTAField
            End Get
            Set
                Me.cUENTAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CBU() As String
            Get
                Return Me.cBUField
            End Get
            Set
                Me.cBUField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIPO() As String
            Get
                Return Me.tIPOField
            End Get
            Set
                Me.tIPOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_CLASES
        
        Private cLASEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASE() As String
            Get
                Return Me.cLASEField
            End Get
            Set
                Me.cLASEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_DIRECCION
        
        Private cODIGO_SAPField As String
        
        Private cODIGO_EXTERNOField As String
        
        Private eS_PRINCIPALField As String
        
        Private cALLEField As String
        
        Private nUMEROField As String
        
        Private pISOField As String
        
        Private dEPARTAMENTOField As String
        
        Private mANZANAField As String
        
        Private mONOBLOCKField As String
        
        Private bARRIOField As String
        
        Private lOTEField As String
        
        Private cODIGO_POSTALField As String
        
        Private cODIGO_POBLACIONField As String
        
        Private pROVINCIAField As String
        
        Private pAISField As String
        
        Private cONTACTOField As ZST_BP_CREATE_IN_WS_CONTACTO
        
        Private cLASESField() As ZST_BP_CREATE_IN_WS_CLASES
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_SAP() As String
            Get
                Return Me.cODIGO_SAPField
            End Get
            Set
                Me.cODIGO_SAPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_EXTERNO() As String
            Get
                Return Me.cODIGO_EXTERNOField
            End Get
            Set
                Me.cODIGO_EXTERNOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ES_PRINCIPAL() As String
            Get
                Return Me.eS_PRINCIPALField
            End Get
            Set
                Me.eS_PRINCIPALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CALLE() As String
            Get
                Return Me.cALLEField
            End Get
            Set
                Me.cALLEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMERO() As String
            Get
                Return Me.nUMEROField
            End Get
            Set
                Me.nUMEROField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PISO() As String
            Get
                Return Me.pISOField
            End Get
            Set
                Me.pISOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DEPARTAMENTO() As String
            Get
                Return Me.dEPARTAMENTOField
            End Get
            Set
                Me.dEPARTAMENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MANZANA() As String
            Get
                Return Me.mANZANAField
            End Get
            Set
                Me.mANZANAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MONOBLOCK() As String
            Get
                Return Me.mONOBLOCKField
            End Get
            Set
                Me.mONOBLOCKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BARRIO() As String
            Get
                Return Me.bARRIOField
            End Get
            Set
                Me.bARRIOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LOTE() As String
            Get
                Return Me.lOTEField
            End Get
            Set
                Me.lOTEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_POSTAL() As String
            Get
                Return Me.cODIGO_POSTALField
            End Get
            Set
                Me.cODIGO_POSTALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_POBLACION() As String
            Get
                Return Me.cODIGO_POBLACIONField
            End Get
            Set
                Me.cODIGO_POBLACIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PROVINCIA() As String
            Get
                Return Me.pROVINCIAField
            End Get
            Set
                Me.pROVINCIAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PAIS() As String
            Get
                Return Me.pAISField
            End Get
            Set
                Me.pAISField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CONTACTO() As ZST_BP_CREATE_IN_WS_CONTACTO
            Get
                Return Me.cONTACTOField
            End Get
            Set
                Me.cONTACTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property CLASES() As ZST_BP_CREATE_IN_WS_CLASES()
            Get
                Return Me.cLASESField
            End Get
            Set
                Me.cLASESField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_IDENT
        
        Private tIPO_DOCField As String
        
        Private nUMERO_DOCField As String
        
        Private vALIDO_DESDEField As String
        
        Private vALIDO_HASTAField As String
        
        Private fECHA_ENTRADAField As String
        
        Private iNSTITUCIONField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIPO_DOC() As String
            Get
                Return Me.tIPO_DOCField
            End Get
            Set
                Me.tIPO_DOCField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMERO_DOC() As String
            Get
                Return Me.nUMERO_DOCField
            End Get
            Set
                Me.nUMERO_DOCField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_DESDE() As String
            Get
                Return Me.vALIDO_DESDEField
            End Get
            Set
                Me.vALIDO_DESDEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_HASTA() As String
            Get
                Return Me.vALIDO_HASTAField
            End Get
            Set
                Me.vALIDO_HASTAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FECHA_ENTRADA() As String
            Get
                Return Me.fECHA_ENTRADAField
            End Get
            Set
                Me.fECHA_ENTRADAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property INSTITUCION() As String
            Get
                Return Me.iNSTITUCIONField
            End Get
            Set
                Me.iNSTITUCIONField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_APODERADO
        
        Private cODIGO_BP_SAPField As String
        
        Private nOMBRESField As String
        
        Private aPELLIDOSField As String
        
        Private tIPO_DOCField As String
        
        Private nUMERO_DOCField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CODIGO_BP_SAP() As String
            Get
                Return Me.cODIGO_BP_SAPField
            End Get
            Set
                Me.cODIGO_BP_SAPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NOMBRES() As String
            Get
                Return Me.nOMBRESField
            End Get
            Set
                Me.nOMBRESField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property APELLIDOS() As String
            Get
                Return Me.aPELLIDOSField
            End Get
            Set
                Me.aPELLIDOSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIPO_DOC() As String
            Get
                Return Me.tIPO_DOCField
            End Get
            Set
                Me.tIPO_DOCField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NUMERO_DOC() As String
            Get
                Return Me.nUMERO_DOCField
            End Get
            Set
                Me.nUMERO_DOCField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_EMPRESA
        
        Private rAZON_SOCIALField As String
        
        Private tIPO_PERSONA_JURIDICAField As String
        
        Private fECHA_INICIO_ACTField As String
        
        Private aPODERADOSField() As ZST_BP_CREATE_IN_WS_APODERADO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property RAZON_SOCIAL() As String
            Get
                Return Me.rAZON_SOCIALField
            End Get
            Set
                Me.rAZON_SOCIALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIPO_PERSONA_JURIDICA() As String
            Get
                Return Me.tIPO_PERSONA_JURIDICAField
            End Get
            Set
                Me.tIPO_PERSONA_JURIDICAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FECHA_INICIO_ACT() As String
            Get
                Return Me.fECHA_INICIO_ACTField
            End Get
            Set
                Me.fECHA_INICIO_ACTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property APODERADOS() As ZST_BP_CREATE_IN_WS_APODERADO()
            Get
                Return Me.aPODERADOSField
            End Get
            Set
                Me.aPODERADOSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_CREATE_IN_WS_PERSONA
        
        Private sEXOField As String
        
        Private nOMBRESField As String
        
        Private aPELLIDOSField As String
        
        Private fECHA_NACIMIENTOField As String
        
        Private nACIONALIDADField As String
        
        Private eSTADO_CIVILField As String
        
        Private lUGAR_NACIMIENTOField As String
        
        Private pROFESIONField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SEXO() As String
            Get
                Return Me.sEXOField
            End Get
            Set
                Me.sEXOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NOMBRES() As String
            Get
                Return Me.nOMBRESField
            End Get
            Set
                Me.nOMBRESField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property APELLIDOS() As String
            Get
                Return Me.aPELLIDOSField
            End Get
            Set
                Me.aPELLIDOSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FECHA_NACIMIENTO() As String
            Get
                Return Me.fECHA_NACIMIENTOField
            End Get
            Set
                Me.fECHA_NACIMIENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NACIONALIDAD() As String
            Get
                Return Me.nACIONALIDADField
            End Get
            Set
                Me.nACIONALIDADField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ESTADO_CIVIL() As String
            Get
                Return Me.eSTADO_CIVILField
            End Get
            Set
                Me.eSTADO_CIVILField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LUGAR_NACIMIENTO() As String
            Get
                Return Me.lUGAR_NACIMIENTOField
            End Get
            Set
                Me.lUGAR_NACIMIENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PROFESION() As String
            Get
                Return Me.pROFESIONField
            End Get
            Set
                Me.pROFESIONField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZST_BP_BU_PARTNERROLE
        
        Private rOLField As String
        
        Private vALIDO_DESDEField As String
        
        Private vALIDO_HASTAField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ROL() As String
            Get
                Return Me.rOLField
            End Get
            Set
                Me.rOLField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_DESDE() As String
            Get
                Return Me.vALIDO_DESDEField
            End Get
            Set
                Me.vALIDO_DESDEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALIDO_HASTA() As String
            Get
                Return Me.vALIDO_HASTAField
            End Get
            Set
                Me.vALIDO_HASTAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZFM_BP_SERVICES_CREATEResponse
        
        Private eS_BP_CREATEField As ZST_BP_CREATE_OUT_WS
        
        Private eS_ERRORField As CVIS_MESSAGE
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ES_BP_CREATE() As ZST_BP_CREATE_OUT_WS
            Get
                Return Me.eS_BP_CREATEField
            End Get
            Set
                Me.eS_BP_CREATEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ES_ERROR() As CVIS_MESSAGE
            Get
                Return Me.eS_ERRORField
            End Get
            Set
                Me.eS_ERRORField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ZFM_BP_SERVICES_CREATECompletedEventHandler(ByVal sender As Object, ByVal e As ZFM_BP_SERVICES_CREATECompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZFM_BP_SERVICES_CREATECompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZFM_BP_SERVICES_CREATEResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZFM_BP_SERVICES_CREATEResponse)
            End Get
        End Property
    End Class
End Namespace
